### ISSUE TITLE
Mobile sub-menu issue

### ISSUE THREAD

**Issue by melbournevijay** [cferdinandi/kraken#260]
Hi Chris,

As illustrated in the image link below, I noticed that your sub menu items disappeared (links in white color?)...

http://www.awesomescreenshot.com/image/1511828/8955c4041daaa13c203c25f7a902d94e

**Comment by cferdinandi** [comment]
Thanks Vijay! I was already aware of this but had yet to create a ticket for it. This issue affects:

- [Keel](https://github.com/cferdinandi/keel)
- [Drop](https://github.com/cferdinandi/drop)

Technically, it doesn't affect Kraken since it's an add-on and not part of the base code, I'll be closing this issue and opening unique ones on the affected projects.

**Comment by cferdinandi** [comment]
This should be addressed with https://github.com/cferdinandi/keel/pull/80 (merge happening in the next few minutes)

**Comment by melbournevijay** [comment]
Thanks Chris!
